import { AnswerChoice, SeedExample } from "./types";

const choices: Record<string, AnswerChoice[]> = {
  official: [
    { id: "A", text: "Click the link quickly before the deadline." },
    { id: "B", text: "Open the official app or website directly." },
    { id: "C", text: "Reply and ask whether the message is real." },
    { id: "D", text: "Forward it to family so they can decide." }
  ],
  payment: [
    { id: "A", text: "Pay the small fee to avoid trouble." },
    { id: "B", text: "Use the official app or call the known support number." },
    { id: "C", text: "Send a screenshot to the sender." },
    { id: "D", text: "Enter card details but use a low-limit card." }
  ],
  provenance: [
    { id: "A", text: "Share it because the image looks real." },
    { id: "B", text: "Search for the earliest source and compare date and location." },
    { id: "C", text: "Ask an AI detector and trust the score." },
    { id: "D", text: "Ignore every image online." }
  ],
  benign: [
    { id: "A", text: "Panic and report the sender as a scammer." },
    { id: "B", text: "Use the official app or known contact path if any action is needed." },
    { id: "C", text: "Forward it with a warning before checking." },
    { id: "D", text: "Reply with private information to be safe." }
  ]
};

export const seedExamples: SeedExample[] = [
  {
    id: "seed-delivery-fee",
    content_type: "sms",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_smishing",
    raw_text: "USPS: Your parcel is held for a $1.49 redelivery fee. Pay now at https://usps-reschedule-pay.com/fee or it returns today.",
    scenario: "A delivery text says your parcel will be returned today unless you pay a small redelivery fee through a link.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "payment_theft",
    risk_level: "high",
    red_flags: ["small unexpected fee", "urgent delivery pressure", "unfamiliar link"],
    safest_action: "Open the official delivery app or website directly instead of using the link.",
    skeptical_claims: [],
    skill_tags: ["urgency_trap", "link_inspection", "payment_safety"],
    answer_choices: choices.payment,
    correct_answer: "B",
    explanation: "The message uses urgency and a low fee to make the link feel harmless. Official delivery apps show real delivery holds."
  },
  {
    id: "seed-bank-verify",
    content_type: "whatsapp",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_impersonation",
    raw_text: "DBS Security: We detected a new login from Kuala Lumpur. Verify now at https://dbs-secure-login-alert.net before your account is suspended.",
    scenario: "A bank alert claims there was a new login and asks you to verify through a link.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "credential_theft",
    risk_level: "high",
    red_flags: ["account suspension threat", "unfamiliar login link", "credential verification request"],
    safest_action: "Do not use the link. Open the bank app directly or call the number on your card.",
    skeptical_claims: [],
    skill_tags: ["credential_safety", "link_inspection", "official_source_check"],
    answer_choices: choices.official,
    correct_answer: "B",
    explanation: "Real bank alerts should be checked through the bank app or known phone number, not a message link."
  },
  {
    id: "seed-toll",
    content_type: "sms",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_smishing",
    raw_text: "Final notice: unpaid road toll of $6.40. Settle immediately at http://ezpass-payments-now.com to avoid penalties.",
    scenario: "A toll message threatens penalties unless a small unpaid balance is paid immediately.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "payment_theft",
    risk_level: "high",
    red_flags: ["penalty threat", "small payment pressure", "non-official payment link"],
    safest_action: "Check toll charges through the official toll agency website or app.",
    skeptical_claims: [],
    skill_tags: ["payment_safety", "urgency_trap", "official_source_check"],
    answer_choices: choices.payment,
    correct_answer: "B",
    explanation: "Small urgent payments are common bait. Use the official toll account portal."
  },
  {
    id: "seed-job",
    content_type: "whatsapp",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_job_scam",
    raw_text: "Remote TikTok review job pays $380/day. Deposit $50 to unlock tasks. Message payroll on WhatsApp now.",
    scenario: "A remote job offer promises high daily pay but requires a deposit before work starts.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "advance_fee_scam",
    risk_level: "high",
    red_flags: ["unrealistic pay", "deposit required", "moves to private messaging"],
    safest_action: "Do not pay. Verify jobs through the company's official careers site.",
    skeptical_claims: [],
    skill_tags: ["too_good_to_be_true", "payment_safety", "official_source_check"],
    answer_choices: choices.payment,
    correct_answer: "B",
    explanation: "Legitimate employers do not require deposits to unlock work."
  },
  {
    id: "seed-family-impersonation",
    content_type: "whatsapp",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_impersonation",
    raw_text: "Hi mom, I dropped my phone and this is my new number. I need $980 for rent today. Please transfer to acct 8832-4411.",
    scenario: "A message claiming to be a family member asks for urgent money from a new number.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "impersonation_payment_theft",
    risk_level: "high",
    red_flags: ["new number", "urgent money request", "account details in chat"],
    safest_action: "Verify through a known number or voice call before sending money.",
    skeptical_claims: [],
    skill_tags: ["impersonation", "payment_safety", "trusted_channel_check"],
    answer_choices: [
      { id: "A", text: "Transfer quickly because it sounds like family." },
      { id: "B", text: "Call the known number or another trusted contact first." },
      { id: "C", text: "Ask for the bank account again." },
      { id: "D", text: "Forward the account details to relatives." }
    ],
    correct_answer: "B",
    explanation: "The safest move is to verify identity through a channel you already trust."
  },
  {
    id: "seed-office365",
    content_type: "email",
    source_dataset: "figshare_derived_pattern",
    original_label: "phishing",
    raw_text: "Subject: Microsoft 365 password expires today. Keep access by signing in at https://office365-renewal-center.com/login.",
    scenario: "An email says your workplace account password expires today and links to a renewal portal.",
    scam_status: "verified_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "credential_theft",
    risk_level: "high",
    red_flags: ["password-expiry pressure", "fake Microsoft domain", "login request"],
    safest_action: "Go to the official workplace sign-in page or ask IT through a known channel.",
    skeptical_claims: [],
    skill_tags: ["credential_safety", "domain_check", "urgency_trap"],
    answer_choices: choices.official,
    correct_answer: "B",
    explanation: "A credential prompt from a lookalike domain is high risk. Use the known workplace portal."
  },
  {
    id: "seed-paypal-refund",
    content_type: "email",
    source_dataset: "figshare_derived_pattern",
    original_label: "phishing",
    raw_text: "PayPal refund pending. Confirm your card at http://paypal-refund-service.info to release $312.22.",
    scenario: "An email claims a PayPal refund is pending and asks you to confirm your card.",
    scam_status: "verified_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "payment_theft",
    risk_level: "high",
    red_flags: ["card confirmation request", "lookalike payment domain", "unexpected refund"],
    safest_action: "Open PayPal directly and check activity there.",
    skeptical_claims: [],
    skill_tags: ["payment_safety", "domain_check", "official_source_check"],
    answer_choices: choices.payment,
    correct_answer: "B",
    explanation: "Payment services do not need a card re-entry from a random email link to release a refund."
  },
  {
    id: "seed-nigerian-fraud",
    content_type: "email",
    source_dataset: "figshare_derived_pattern",
    original_label: "nigerian_fraud",
    raw_text: "I am the estate officer for a deceased oil minister. Your assistance will release USD 8.5M. Send ID and bank details urgently.",
    scenario: "A stranger offers a share of a large inheritance if you send identity and bank details.",
    scam_status: "verified_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "advance_fee_identity_theft",
    risk_level: "high",
    red_flags: ["stranger offers large payout", "requests ID and bank details", "urgent secrecy"],
    safest_action: "Do not reply or send documents. Report and delete the message.",
    skeptical_claims: [],
    skill_tags: ["too_good_to_be_true", "identity_safety", "reporting"],
    answer_choices: [
      { id: "A", text: "Ask for proof and send a partial ID." },
      { id: "B", text: "Do not reply; report and delete it." },
      { id: "C", text: "Share bank details but no password." },
      { id: "D", text: "Forward it to a friend who needs money." }
    ],
    correct_answer: "B",
    explanation: "Unexpected windfalls that need private documents are classic advance-fee and identity theft bait."
  },
  {
    id: "seed-crypto-wallet",
    content_type: "social_post",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_crypto_scam",
    raw_text: "Airdrop closes in 30 minutes. Connect wallet and approve token access at https://airdrop-bonus-claim.io.",
    scenario: "A social post advertises an urgent crypto airdrop and asks users to connect a wallet.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "wallet_drainer",
    risk_level: "high",
    red_flags: ["airdrop urgency", "wallet connection request", "unfamiliar domain"],
    safest_action: "Do not connect a wallet. Verify through the project's official channels.",
    skeptical_claims: [],
    skill_tags: ["wallet_safety", "link_inspection", "urgency_trap"],
    answer_choices: choices.official,
    correct_answer: "B",
    explanation: "Wallet approvals can grant asset access. Verify airdrops through official project channels."
  },
  {
    id: "seed-government-grant",
    content_type: "sms",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_government_scam",
    raw_text: "Gov relief grant approved. Claim $780 before midnight at https://benefits-gov-claim.com using your SSN.",
    scenario: "A government grant text says money is approved but asks for SSN through a link.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "identity_theft",
    risk_level: "high",
    red_flags: ["government impersonation", "SSN request", "deadline pressure"],
    safest_action: "Use the official government benefits site typed manually into the browser.",
    skeptical_claims: [],
    skill_tags: ["identity_safety", "official_source_check", "urgency_trap"],
    answer_choices: choices.official,
    correct_answer: "B",
    explanation: "Sensitive government identifiers should never be entered through an unsolicited link."
  },
  {
    id: "seed-phishing-url-login",
    content_type: "url",
    source_dataset: "phiusiil_derived_pattern",
    original_label: "phishing_url",
    raw_text: "https://secure-amazon-billing-login.com/ap/signin",
    scenario: "A link looks like an Amazon billing login but the registered domain is not Amazon.",
    scam_status: "verified_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "credential_theft",
    risk_level: "high",
    red_flags: ["brand name inside fake domain", "login path", "billing pressure"],
    safest_action: "Type amazon.com manually or use the official app.",
    skeptical_claims: [],
    skill_tags: ["domain_check", "link_inspection", "credential_safety"],
    answer_choices: choices.official,
    correct_answer: "B",
    explanation: "The real domain is not Amazon. Brand words inside a longer domain do not make it safe."
  },
  {
    id: "seed-phishing-url-shortener",
    content_type: "url",
    source_dataset: "phiusiil_derived_pattern",
    original_label: "phishing_url",
    raw_text: "https://bit.ly/free-bank-verification-now",
    scenario: "A shortened link claims to lead to bank verification.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "malicious_link",
    risk_level: "medium",
    red_flags: ["shortened destination", "bank verification claim", "unrequested action"],
    safest_action: "Avoid the short link and go to the bank app directly.",
    skeptical_claims: [],
    skill_tags: ["link_inspection", "official_source_check"],
    answer_choices: choices.official,
    correct_answer: "B",
    explanation: "Short links hide the destination. Account verification should happen in the official app."
  },
  {
    id: "seed-legit-bank-notice",
    content_type: "sms",
    source_dataset: "benign_contrast_seed",
    original_label: "legitimate",
    raw_text: "Your bank statement is ready. Open your banking app or visit the official website if you want to view it. No reply needed.",
    scenario: "A bank notice says a statement is ready and tells you to use the official app, without a link.",
    scam_status: "legitimate",
    scope_status: "benign_contrast",
    threat_type: "none",
    risk_level: "low",
    red_flags: [],
    safest_action: "Use the official app if you want to check the statement.",
    skeptical_claims: ["Account messages should still be handled in official channels."],
    skill_tags: ["benign_contrast", "official_source_check"],
    answer_choices: choices.benign,
    correct_answer: "B",
    explanation: "This is a lower-risk notice because it pushes you toward an official channel and asks for no secrets."
  },
  {
    id: "seed-legit-delivery",
    content_type: "sms",
    source_dataset: "benign_contrast_seed",
    original_label: "legitimate",
    raw_text: "Your package was delivered at 2:14 PM. Check the official carrier app for photo proof.",
    scenario: "A delivery notification says a package was delivered and points to the official carrier app.",
    scam_status: "legitimate",
    scope_status: "benign_contrast",
    threat_type: "none",
    risk_level: "low",
    red_flags: [],
    safest_action: "Check the carrier app if you need confirmation.",
    skeptical_claims: ["Delivery messages with links or payment requests deserve extra scrutiny."],
    skill_tags: ["benign_contrast", "official_source_check"],
    answer_choices: choices.benign,
    correct_answer: "B",
    explanation: "No payment, login, or private details are requested."
  },
  {
    id: "seed-out-of-scope-sale",
    content_type: "email",
    source_dataset: "spam_boundary_seed",
    original_label: "advertising_spam",
    raw_text: "Mega weekend sale: 20% off home goods. Use coupon SPRING20 in store or online.",
    scenario: "A retail email advertises a weekend coupon.",
    scam_status: "legitimate",
    scope_status: "out_of_scope_spam",
    threat_type: "generic_spam",
    risk_level: "low",
    red_flags: [],
    safest_action: "Ignore it or unsubscribe through official sender controls.",
    skeptical_claims: ["This is advertising noise, not a phishing or scam drill."],
    skill_tags: ["scope_boundary"],
    answer_choices: choices.benign,
    correct_answer: "B",
    explanation: "This may be unwanted, but generic advertising is not the same as phishing."
  },
  {
    id: "seed-source-photo",
    content_type: "social_post",
    source_dataset: "exa_source_pack_seed",
    original_label: "provenance_drill",
    raw_text: "This flood photo is being shared as today's storm in Singapore. Share widely.",
    scenario: "A dramatic flood photo is being shared as if it happened today in your city.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "misleading_provenance_scam",
    risk_level: "medium",
    red_flags: ["date/location claim", "pressure to share", "no source shown"],
    safest_action: "Look for the earliest source and compare date, location, and publisher before sharing.",
    skeptical_claims: ["The image may be real but used in the wrong context."],
    skill_tags: ["provenance_check", "pause_before_sharing", "source_verification"],
    answer_choices: choices.provenance,
    correct_answer: "B",
    explanation: "The lesson is provenance, not guessing whether pixels are AI-generated."
  },
  {
    id: "seed-fake-charity",
    content_type: "social_post",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_charity_scam",
    raw_text: "Emergency charity drive for storm victims. Send donations by crypto wallet now. No website due to urgent response.",
    scenario: "A charity post asks for urgent crypto donations but provides no verifiable organization page.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "charity_scam",
    risk_level: "high",
    red_flags: ["urgent donation pressure", "crypto-only payment", "no verifiable organization"],
    safest_action: "Donate only through the official website of a known charity.",
    skeptical_claims: [],
    skill_tags: ["payment_safety", "source_verification", "urgency_trap"],
    answer_choices: choices.payment,
    correct_answer: "B",
    explanation: "Real emergencies still need verifiable donation channels."
  },
  {
    id: "seed-marketplace",
    content_type: "social_post",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_marketplace_scam",
    raw_text: "Buyer says payment is escrowed. Click https://marketplace-safe-release.net and enter card info to receive funds.",
    scenario: "A marketplace buyer says your payment is escrowed and asks you to enter card details to receive funds.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "payment_theft",
    risk_level: "high",
    red_flags: ["fake escrow claim", "card details to receive money", "off-platform link"],
    safest_action: "Keep payment and messaging inside the official marketplace app.",
    skeptical_claims: [],
    skill_tags: ["payment_safety", "platform_safety", "link_inspection"],
    answer_choices: choices.payment,
    correct_answer: "B",
    explanation: "Receiving money should not require card details through an off-platform link."
  },
  {
    id: "seed-school-portal",
    content_type: "email",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_credential_scam",
    raw_text: "School portal update required. Parent access closes tonight. Sign in at https://schoolportal-reset-login.com.",
    scenario: "A school portal email warns parent access closes tonight unless you sign in through a link.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "credential_theft",
    risk_level: "high",
    red_flags: ["parent anxiety", "account closure threat", "unfamiliar school portal domain"],
    safest_action: "Use the known school portal URL or contact the school office.",
    skeptical_claims: [],
    skill_tags: ["credential_safety", "official_source_check", "urgency_trap"],
    answer_choices: choices.official,
    correct_answer: "B",
    explanation: "School-account issues should be handled through known school channels."
  },
  {
    id: "seed-airline",
    content_type: "sms",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_travel_scam",
    raw_text: "Flight refund approved. Confirm passenger details and card at http://airline-refund-center.co within 2 hours.",
    scenario: "An airline refund text asks for passenger details and card information through a link.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "identity_payment_theft",
    risk_level: "high",
    red_flags: ["unexpected refund", "card and passenger details", "two-hour deadline"],
    safest_action: "Check the booking in the airline app or website typed manually.",
    skeptical_claims: [],
    skill_tags: ["identity_safety", "payment_safety", "official_source_check"],
    answer_choices: choices.payment,
    correct_answer: "B",
    explanation: "Refund details should be verified inside the actual airline account."
  },
  {
    id: "seed-tax",
    content_type: "email",
    source_dataset: "synthetic_seed",
    original_label: "synthetic_tax_scam",
    raw_text: "Tax refund recalculated. Submit banking and ID at https://irs-refund-update-fast.com before final processing.",
    scenario: "A tax refund email asks you to submit banking and ID information through a link.",
    scam_status: "suspected_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "identity_payment_theft",
    risk_level: "high",
    red_flags: ["tax authority impersonation", "banking and ID request", "fake refund domain"],
    safest_action: "Use the official tax agency website typed manually.",
    skeptical_claims: [],
    skill_tags: ["identity_safety", "domain_check", "official_source_check"],
    answer_choices: choices.official,
    correct_answer: "B",
    explanation: "Tax agencies do not need sensitive details through random refund links."
  },
  {
    id: "seed-benign-event",
    content_type: "email",
    source_dataset: "benign_contrast_seed",
    original_label: "legitimate",
    raw_text: "Community center reminder: Saturday safety workshop starts at 10 AM. No registration link is required.",
    scenario: "A community reminder gives event timing and asks for no payment, login, or private details.",
    scam_status: "legitimate",
    scope_status: "benign_contrast",
    threat_type: "none",
    risk_level: "low",
    red_flags: [],
    safest_action: "No action needed unless you want to confirm through the community center's known page.",
    skeptical_claims: ["Benign messages can still be checked through known channels if uncertain."],
    skill_tags: ["benign_contrast", "low_risk_notice"],
    answer_choices: choices.benign,
    correct_answer: "B",
    explanation: "There is no urgency, payment request, login link, or private-data request."
  },
  {
    id: "seed-social-account",
    content_type: "email",
    source_dataset: "figshare_derived_pattern",
    original_label: "phishing",
    raw_text: "Instagram copyright strike. Appeal within 12 hours at https://instagram-copyright-helpdesk.com or your account will be deleted.",
    scenario: "A social account notice threatens deletion unless you appeal through a link.",
    scam_status: "verified_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "credential_theft",
    risk_level: "high",
    red_flags: ["copyright panic", "account deletion threat", "fake helpdesk domain"],
    safest_action: "Open the social app directly and check account status there.",
    skeptical_claims: [],
    skill_tags: ["credential_safety", "domain_check", "urgency_trap"],
    answer_choices: choices.official,
    correct_answer: "B",
    explanation: "Account warnings should be verified inside the official app."
  },
  {
    id: "seed-invoice",
    content_type: "email",
    source_dataset: "figshare_derived_pattern",
    original_label: "phishing",
    raw_text: "Attached invoice overdue. Download statement at http://invoice-cloud-docs.net/payments and settle today.",
    scenario: "An unexpected invoice email pushes you to download a statement and settle today.",
    scam_status: "verified_scam",
    scope_status: "in_scope_phishing_or_scam",
    threat_type: "malicious_link",
    risk_level: "medium",
    red_flags: ["unexpected invoice", "download link", "same-day payment pressure"],
    safest_action: "Verify the invoice through the known vendor contact before opening links.",
    skeptical_claims: [],
    skill_tags: ["link_inspection", "vendor_verification", "urgency_trap"],
    answer_choices: choices.official,
    correct_answer: "B",
    explanation: "Unexpected invoices should be checked through known vendor channels."
  }
];

export const openingExample = seedExamples[0];
